class Player:
    def __init__(self, player: dict):
        self.id = 0 #player['ID']
        self.name = player['Player']
        self.position = player['POS']
        self.team = player['Team']
        # self.pass_attempts = player['PASS_ATT']
        self.pass_yards = player['PASSYDS']
        self.pass_tds = player['PASSTDS']
        # self.rush_attempts = player['RUSH_ATT']
        self.rush_yards = player['RUSHYDS']
        self.rush_tds = player['RUSHTDS']
        self.receptions = player['REC']
        self.rec_yards = player['RECYDS']
        self.rec_tds = player['RECTDS']
        self.interceptions = player['INT']
        self.fumbles = player['FUM']
        self.fumbles_lost = player['FUM_LOST']
        self.kicker_pts = player['KICKER_PTS']
        self.def_pts = player['DEF_PTS']
        self.fpts = player['FPTS']
        self.vorp = player['VORP']
        self.adp = player['ADP']