class Player:
    def __init__(self, player: dict):
        self.id = player['ID']
        self.name = player['Player']
        self.position = player['POS']
        self.team = player['Team']
        self.pass_attempts = player['PASS_ATT']
        self.pass_yards = player['PASS_YDS']
        self.pass_tds = player['PASS_TDS']
        self.rush_attempts = player['RUSH_ATT']
        self.rush_yards = player['RUSH_YDS']
        self.rush_tds = player['RUSH_TDS']
        self.receptions = player['REC']
        self.rec_yards = player['REC_YDS']
        self.rec_tds = player['REC_TDS']
        self.interceptions = player['INT']
        self.fumbles = player['FUM']
        self.kicker_pts = player['KICKER_PTS']
        self.def_pts = player['DEF_PTS']
        self.fpts = player['FPTS']
        self.vorp = player['VORP']
        self.adp = player['ADP']